version: '3.8'

services:
  web:
    build: .
    container_name: dental_web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - MYSQL_HOST=db
      - MYSQL_USER=ecommerce_user
      - MYSQL_PASSWORD=secret_password
      - MYSQL_DB=ecommerce_db

      # --- AGREGÁ ESTO PARA QUE NO EXPLOTE ---
      - MP_ACCESS_TOKEN=APP_USR-1406867289039041-011308-01d185d294d784192a9ad6af84807a51-3130462005
      - MP_PUBLIC_KEY=APP_USR-6b1bb09e-fd95-44eb-bd86-43d0a5795a96
      - BASE_URL=http://localhost:5000
      # ---------------------------------------

    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: dental_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: secret_password
    ports:
      - "3307:3306"
    volumes:
      - dental_mysql_data:/var/lib/mysql

volumes:
  dental_mysql_data:
