version: '3.8'

services:
  web:
    build: .
    container_name: dental_web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=${FLASK_DEBUG}
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}

      # --- SEGURIDAD: Ahora lee del archivo .env ---
      - MP_ACCESS_TOKEN=${MP_ACCESS_TOKEN}
      - MP_PUBLIC_KEY=${MP_PUBLIC_KEY}
      - BASE_URL=${BASE_URL}
      # ---------------------------------------------

    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: dental_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - dental_mysql_data:/var/lib/mysql

volumes:
  dental_mysql_data:
